spring:
  application:
    name: spring-boot-integration-tcp-client
  banner:
    image:
      location: classpath:banner.txt

server:
  port: 8082

tcp:
  server:
    host: localhost
    port: 9898
  client:
    port: 8989
    timeout: 10000
    poolSize: 5