spring:
  application:
    name: spring-boot-integration-tcp-ip-client

server:
  port: 8082
  servlet:
    context-path: /api
  error:
    include-message: always

tcp:
  server:
    host: localhost
    port: 10001
  client:
    connection:
      poolSize: 50