spring:
  application:
    name: spring-boot-integration-tcp-server
  banner:
    image:
      location: classpath:banner.txt

server:
  port: 8081

tcp:
  server:
    port: 9898
  client:
    host: localhost
    port: 8989
    timeout: 15000
    poolSize: 5